-- ----------------------------
-- Table structure for tb_sys_auth_role
-- ----------------------------
DROP TABLE IF EXISTS `tb_sys_auth_role`;
CREATE TABLE `tb_sys_auth_role` (`id` int(11) generated by default as identity (start with 1) COMMENT '主键',
                                    `name` varchar(16) NOT NULL COMMENT '角色名',
                                    PRIMARY KEY (`id`));

-- ----------------------------
-- Table structure for tb_sys_auth_user
-- ----------------------------
DROP TABLE IF EXISTS `tb_sys_auth_user`;
CREATE TABLE `tb_sys_auth_user` (`id` int(11) generated by default as identity (start with 1)  COMMENT '主键',
                                    `username` varchar(255) NOT NULL COMMENT '用户名',
                                    `password` varchar(255) DEFAULT NULL COMMENT '密码',
                                    PRIMARY KEY (`id`));

-- ----------------------------
-- Table structure for tb_sys_auth_user_role
-- ----------------------------
DROP TABLE IF EXISTS `tb_sys_auth_user_role`;
CREATE TABLE `tb_sys_auth_user_role` (`id` int(11) generated by default as identity (start with 1),
                                              `user_id` int(11) NOT NULL COMMENT '权限用户id，关联tb_sys_auth_user表的id',
                                              `role_id` int(11) NOT NULL COMMENT '权限角色id，关联tb_sys_auth_role表的id',
                                              PRIMARY KEY (`id`));


-- ----------------------------
-- Table structure for tb_sys_client_detail
-- ----------------------------
DROP TABLE IF EXISTS `tb_sys_client_detail`;
CREATE TABLE `tb_sys_client_detail` (
                                        `id` int(11) generated by default as identity (start with 1) COMMENT '主键',
                                        `client_id` varchar(32) NOT NULL DEFAULT '' COMMENT '客户端id',
                                        `access_token_validity_seconds` int(11) NOT NULL DEFAULT '0' COMMENT 'access_token有效期',
                                        `additional_information` varchar(64) NOT NULL DEFAULT '' COMMENT '额外信息',
                                        `authorities` varchar(128) NOT NULL DEFAULT '' COMMENT '授权列表',
                                        `authorized_grant_types` varchar(64) NOT NULL DEFAULT '' COMMENT '授权类型',
                                        `auto_approve` varchar(32) NOT NULL DEFAULT '' COMMENT '自动通过的作用域',
                                        `client_secret` varchar(128) NOT NULL DEFAULT '' COMMENT '客户端密钥',
                                        `refresh_token_validity_seconds` bigint(20) NOT NULL DEFAULT '0' COMMENT 'refresh_token有效期',
                                        `registered_redirect_uri` varchar(128) NOT NULL DEFAULT '' COMMENT '跳转url',
                                        `resource_ids` varchar(64) NOT NULL DEFAULT '' COMMENT '资源列表',
                                        `scope` varchar(64) NOT NULL DEFAULT '' COMMENT '作用域',
                                        `scoped` int(11) NOT NULL DEFAULT '1' COMMENT '是否需要被控制',
                                        `secret_required` int(11) NOT NULL DEFAULT '1' COMMENT '是否需要密钥',
                                        PRIMARY KEY (`id`));
